#!/usr/bin/env python3
"""Convert a GIF (or a series of PNGs) into an LVGL animation asset.

Produces a C file in the same LV_IMG_CF_INDEXED_1BIT format as the existing
assets in boards/shields/nice_oled/assets/ (8-byte palette honoring
CONFIG_NICE_OLED_WIDGET_INVERTED, MSB-first 1-bit rows padded to a byte),
plus the frame-pointer array consumed by the peripheral USER animation slot:

    const lv_img_dsc_t *user_anim_imgs[];
    const uint8_t user_anim_imgs_count;

The output is byte-compatible with LVGL's official image converter
(https://lvgl.io/tools/imageconverter, color format CF_INDEXED_1_BIT); use
that tool instead if you prefer, and only add the array/count by hand.

Usage:
    python3 scripts/gif2anim.py input.gif --name orbit \
        -o boards/shields/nice_oled/assets/user_animation.c

    python3 scripts/gif2anim.py frame*.png --name orbit --width 48

Requires: Pillow (pip install Pillow)
"""

import argparse
import os
import sys

from PIL import Image, ImageSequence

CANVAS_WIDTH = 68  # portrait canvas of the nice_oled shield
MAX_FRAMES = 254   # lv_animimg_set_src takes a uint8_t count


def load_frames(paths):
    frames = []
    for path in paths:
        img = Image.open(path)
        if getattr(img, "is_animated", False):
            for frame in ImageSequence.Iterator(img):
                frames.append(frame.convert("L"))
        else:
            frames.append(img.convert("L"))
    return frames


def to_1bit(frame, width, height, threshold, dither, invert):
    if width or height:
        w, h = frame.size
        if width and not height:
            height = max(1, round(h * width / w))
        elif height and not width:
            width = max(1, round(w * height / h))
        frame = frame.resize((width, height), Image.LANCZOS)
    if dither:
        return frame.convert("1"), invert
    return frame.point(lambda p: 255 if p >= threshold else 0).convert("1"), invert


def pack_indexed_1bit(frame, invert):
    w, h = frame.size
    row_bytes = (w + 7) // 8
    data = bytearray(row_bytes * h)
    px = frame.load()
    for y in range(h):
        for x in range(w):
            # Dark source pixel -> palette index 1 (foreground), like the
            # shipped assets. --invert flips this.
            bit = px[x, y] == 0
            if invert:
                bit = not bit
            if bit:
                data[y * row_bytes + x // 8] |= 0x80 >> (x % 8)
    return bytes(data)


def emit_c(frames_1bit, name, out):
    lines = [
        "/* Generated by scripts/gif2anim.py — LV_IMG_CF_INDEXED_1BIT frames",
        " * for CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_USER. */",
        "#include <lvgl.h>",
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
    ]
    for i, (frame, data) in enumerate(frames_1bit):
        w, h = frame.size
        sym = f"{name}_{i:02d}"
        lines.append(f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {sym}_map[] = {{")
        lines.append("#if CONFIG_NICE_OLED_WIDGET_INVERTED")
        lines.append("  0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff, /*palette*/")
        lines.append("#else")
        lines.append("  0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff, /*palette*/")
        lines.append("#endif")
        for off in range(0, len(data), 16):
            chunk = ", ".join(f"0x{b:02x}" for b in data[off:off + 16])
            lines.append(f"  {chunk},")
        lines.append("};")
        lines.append("")
        lines.append(f"static const lv_img_dsc_t {sym} = {{")
        lines.append("  .header.cf = LV_IMG_CF_INDEXED_1BIT,")
        lines.append("  .header.always_zero = 0,")
        lines.append("  .header.reserved = 0,")
        lines.append(f"  .header.w = {w},")
        lines.append(f"  .header.h = {h},")
        lines.append(f"  .data_size = {8 + len(data)},")
        lines.append(f"  .data = {sym}_map,")
        lines.append("};")
        lines.append("")
    refs = ", ".join(f"&{name}_{i:02d}" for i in range(len(frames_1bit)))
    lines.append(f"const lv_img_dsc_t *user_anim_imgs[] = {{{refs}}};")
    lines.append(f"const uint8_t user_anim_imgs_count = {len(frames_1bit)};")
    lines.append("")
    with open(out, "w") as f:
        f.write("\n".join(lines))


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("inputs", nargs="+", help="GIF file or PNG frames")
    p.add_argument("--name", default="user_anim", help="C symbol prefix")
    p.add_argument("-o", "--out", default="boards/shields/nice_oled/assets/user_animation.c")
    p.add_argument("--width", type=int, help=f"resize to width (canvas is {CANVAS_WIDTH} wide)")
    p.add_argument("--height", type=int, help="resize to height")
    p.add_argument("--threshold", type=int, default=128, help="black/white cutoff 0-255")
    p.add_argument("--dither", action="store_true", help="Floyd-Steinberg dithering")
    p.add_argument("--invert", action="store_true", help="swap foreground/background")
    p.add_argument("--fps", type=float, default=8.0, help="target playback fps (for the suggested config)")
    args = p.parse_args()

    frames = load_frames(args.inputs)
    if not frames:
        sys.exit("no frames found")
    if len(frames) > MAX_FRAMES:
        sys.exit(f"{len(frames)} frames exceeds the {MAX_FRAMES} frame limit")

    frames_1bit = []
    for frame in frames:
        fr, inv = to_1bit(frame, args.width, args.height, args.threshold, args.dither, args.invert)
        frames_1bit.append((fr, pack_indexed_1bit(fr, inv)))

    w, h = frames_1bit[0][0].size
    if w > CANVAS_WIDTH:
        print(f"warning: frame width {w} exceeds the {CANVAS_WIDTH}px canvas; use --width", file=sys.stderr)

    emit_c(frames_1bit, args.name, args.out)

    flash = sum(8 + len(d) for _, d in frames_1bit)
    n = len(frames_1bit)
    cycle_ms = round(n / args.fps * 1000)
    print(f"wrote {args.out}: {n} frames {w}x{h}, ~{flash / 1024:.1f} KB flash")
    print("add to your keyboard .conf:")
    print("  CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_USER=y")
    print(f"  CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS={cycle_ms}"
          f"  # full cycle, {n} frames at ~{args.fps:g} fps")


if __name__ == "__main__":
    main()
